# Generated by Django 3.1.12 on 2024-12-01 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_auto_20241128_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('Currently Reading', 'Currently Reading'), ('Finished', 'Finished'), ('Want to Read', 'Want to Read')], default='Want to Read', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reading_challenge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
