# Generated by Django 3.1.12 on 2024-12-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_book_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reading_challenge',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reading_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
