# Generated by Django 3.1.12 on 2024-12-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20241202_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
